// Code generated by ent, DO NOT EDIT.

package paymenttransactionclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymenttransactionclaim type in the database.
	Label = "payment_transaction_claim"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTxHash holds the string denoting the tx_hash field in the database.
	FieldTxHash = "tx_hash"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldTransferTime holds the string denoting the transfer_time field in the database.
	FieldTransferTime = "transfer_time"
	// FieldOrderCreatedAt holds the string denoting the order_created_at field in the database.
	FieldOrderCreatedAt = "order_created_at"
	// FieldOrderWindowEnd holds the string denoting the order_window_end field in the database.
	FieldOrderWindowEnd = "order_window_end"
	// FieldReviewPending holds the string denoting the review_pending field in the database.
	FieldReviewPending = "review_pending"
	// FieldEvidence holds the string denoting the evidence field in the database.
	FieldEvidence = "evidence"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the paymenttransactionclaim in the database.
	Table = "payment_transaction_claims"
)

// Columns holds all SQL columns for paymenttransactionclaim fields.
var Columns = []string{
	FieldID,
	FieldTxHash,
	FieldOrderID,
	FieldSource,
	FieldTransferTime,
	FieldOrderCreatedAt,
	FieldOrderWindowEnd,
	FieldReviewPending,
	FieldEvidence,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TxHashValidator is a validator for the "tx_hash" field. It is called by the builders before save.
	TxHashValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultReviewPending holds the default value on creation for the "review_pending" field.
	DefaultReviewPending bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentTransactionClaim queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTxHash orders the results by the tx_hash field.
func ByTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxHash, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByTransferTime orders the results by the transfer_time field.
func ByTransferTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransferTime, opts...).ToFunc()
}

// ByOrderCreatedAt orders the results by the order_created_at field.
func ByOrderCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderCreatedAt, opts...).ToFunc()
}

// ByOrderWindowEnd orders the results by the order_window_end field.
func ByOrderWindowEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderWindowEnd, opts...).ToFunc()
}

// ByReviewPending orders the results by the review_pending field.
func ByReviewPending(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewPending, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
