// Code generated by ent, DO NOT EDIT.

package paymenttransactionclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldID, id))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTxHash, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContainsFold(FieldTxHash, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldOrderID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.NotPredicates(p))
}
