// Code generated by ent, DO NOT EDIT.

package paymenttransactionclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldID, id))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTxHash, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldSource, v))
}

// TransferTime applies equality check predicate on the "transfer_time" field. It's identical to TransferTimeEQ.
func TransferTime(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTransferTime, v))
}

// OrderCreatedAt applies equality check predicate on the "order_created_at" field. It's identical to OrderCreatedAtEQ.
func OrderCreatedAt(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderCreatedAt, v))
}

// OrderWindowEnd applies equality check predicate on the "order_window_end" field. It's identical to OrderWindowEndEQ.
func OrderWindowEnd(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderWindowEnd, v))
}

// ReviewPending applies equality check predicate on the "review_pending" field. It's identical to ReviewPendingEQ.
func ReviewPending(v bool) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldReviewPending, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContainsFold(FieldTxHash, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldOrderID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldContainsFold(FieldSource, v))
}

// TransferTimeEQ applies the EQ predicate on the "transfer_time" field.
func TransferTimeEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldTransferTime, v))
}

// TransferTimeNEQ applies the NEQ predicate on the "transfer_time" field.
func TransferTimeNEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldTransferTime, v))
}

// TransferTimeIn applies the In predicate on the "transfer_time" field.
func TransferTimeIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldTransferTime, vs...))
}

// TransferTimeNotIn applies the NotIn predicate on the "transfer_time" field.
func TransferTimeNotIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldTransferTime, vs...))
}

// TransferTimeGT applies the GT predicate on the "transfer_time" field.
func TransferTimeGT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldTransferTime, v))
}

// TransferTimeGTE applies the GTE predicate on the "transfer_time" field.
func TransferTimeGTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldTransferTime, v))
}

// TransferTimeLT applies the LT predicate on the "transfer_time" field.
func TransferTimeLT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldTransferTime, v))
}

// TransferTimeLTE applies the LTE predicate on the "transfer_time" field.
func TransferTimeLTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldTransferTime, v))
}

// TransferTimeIsNil applies the IsNil predicate on the "transfer_time" field.
func TransferTimeIsNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIsNull(FieldTransferTime))
}

// TransferTimeNotNil applies the NotNil predicate on the "transfer_time" field.
func TransferTimeNotNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotNull(FieldTransferTime))
}

// OrderCreatedAtEQ applies the EQ predicate on the "order_created_at" field.
func OrderCreatedAtEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderCreatedAt, v))
}

// OrderCreatedAtNEQ applies the NEQ predicate on the "order_created_at" field.
func OrderCreatedAtNEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldOrderCreatedAt, v))
}

// OrderCreatedAtIn applies the In predicate on the "order_created_at" field.
func OrderCreatedAtIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldOrderCreatedAt, vs...))
}

// OrderCreatedAtNotIn applies the NotIn predicate on the "order_created_at" field.
func OrderCreatedAtNotIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldOrderCreatedAt, vs...))
}

// OrderCreatedAtGT applies the GT predicate on the "order_created_at" field.
func OrderCreatedAtGT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldOrderCreatedAt, v))
}

// OrderCreatedAtGTE applies the GTE predicate on the "order_created_at" field.
func OrderCreatedAtGTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldOrderCreatedAt, v))
}

// OrderCreatedAtLT applies the LT predicate on the "order_created_at" field.
func OrderCreatedAtLT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldOrderCreatedAt, v))
}

// OrderCreatedAtLTE applies the LTE predicate on the "order_created_at" field.
func OrderCreatedAtLTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldOrderCreatedAt, v))
}

// OrderCreatedAtIsNil applies the IsNil predicate on the "order_created_at" field.
func OrderCreatedAtIsNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIsNull(FieldOrderCreatedAt))
}

// OrderCreatedAtNotNil applies the NotNil predicate on the "order_created_at" field.
func OrderCreatedAtNotNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotNull(FieldOrderCreatedAt))
}

// OrderWindowEndEQ applies the EQ predicate on the "order_window_end" field.
func OrderWindowEndEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldOrderWindowEnd, v))
}

// OrderWindowEndNEQ applies the NEQ predicate on the "order_window_end" field.
func OrderWindowEndNEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldOrderWindowEnd, v))
}

// OrderWindowEndIn applies the In predicate on the "order_window_end" field.
func OrderWindowEndIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldOrderWindowEnd, vs...))
}

// OrderWindowEndNotIn applies the NotIn predicate on the "order_window_end" field.
func OrderWindowEndNotIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldOrderWindowEnd, vs...))
}

// OrderWindowEndGT applies the GT predicate on the "order_window_end" field.
func OrderWindowEndGT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldOrderWindowEnd, v))
}

// OrderWindowEndGTE applies the GTE predicate on the "order_window_end" field.
func OrderWindowEndGTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldOrderWindowEnd, v))
}

// OrderWindowEndLT applies the LT predicate on the "order_window_end" field.
func OrderWindowEndLT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldOrderWindowEnd, v))
}

// OrderWindowEndLTE applies the LTE predicate on the "order_window_end" field.
func OrderWindowEndLTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldOrderWindowEnd, v))
}

// OrderWindowEndIsNil applies the IsNil predicate on the "order_window_end" field.
func OrderWindowEndIsNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIsNull(FieldOrderWindowEnd))
}

// OrderWindowEndNotNil applies the NotNil predicate on the "order_window_end" field.
func OrderWindowEndNotNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotNull(FieldOrderWindowEnd))
}

// ReviewPendingEQ applies the EQ predicate on the "review_pending" field.
func ReviewPendingEQ(v bool) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldReviewPending, v))
}

// ReviewPendingNEQ applies the NEQ predicate on the "review_pending" field.
func ReviewPendingNEQ(v bool) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldReviewPending, v))
}

// EvidenceIsNil applies the IsNil predicate on the "evidence" field.
func EvidenceIsNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIsNull(FieldEvidence))
}

// EvidenceNotNil applies the NotNil predicate on the "evidence" field.
func EvidenceNotNil() predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotNull(FieldEvidence))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentTransactionClaim) predicate.PaymentTransactionClaim {
	return predicate.PaymentTransactionClaim(sql.NotPredicates(p))
}
