// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/intentrouter"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// IntentRouterCreate is the builder for creating a IntentRouter entity.
type IntentRouterCreate struct {
	config
	mutation *IntentRouterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntentRouterCreate) SetCreatedAt(v time.Time) *IntentRouterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableCreatedAt(v *time.Time) *IntentRouterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntentRouterCreate) SetUpdatedAt(v time.Time) *IntentRouterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableUpdatedAt(v *time.Time) *IntentRouterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *IntentRouterCreate) SetGroupID(v int64) *IntentRouterCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *IntentRouterCreate) SetEnabled(v bool) *IntentRouterCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableEnabled(v *bool) *IntentRouterCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (_c *IntentRouterCreate) SetClassifierBaseURL(v string) *IntentRouterCreate {
	_c.mutation.SetClassifierBaseURL(v)
	return _c
}

// SetNillableClassifierBaseURL sets the "classifier_base_url" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableClassifierBaseURL(v *string) *IntentRouterCreate {
	if v != nil {
		_c.SetClassifierBaseURL(*v)
	}
	return _c
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (_c *IntentRouterCreate) SetClassifierAPIKey(v string) *IntentRouterCreate {
	_c.mutation.SetClassifierAPIKey(v)
	return _c
}

// SetNillableClassifierAPIKey sets the "classifier_api_key" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableClassifierAPIKey(v *string) *IntentRouterCreate {
	if v != nil {
		_c.SetClassifierAPIKey(*v)
	}
	return _c
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (_c *IntentRouterCreate) SetClassifierProtocol(v string) *IntentRouterCreate {
	_c.mutation.SetClassifierProtocol(v)
	return _c
}

// SetNillableClassifierProtocol sets the "classifier_protocol" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableClassifierProtocol(v *string) *IntentRouterCreate {
	if v != nil {
		_c.SetClassifierProtocol(*v)
	}
	return _c
}

// SetClassifierModel sets the "classifier_model" field.
func (_c *IntentRouterCreate) SetClassifierModel(v string) *IntentRouterCreate {
	_c.mutation.SetClassifierModel(v)
	return _c
}

// SetNillableClassifierModel sets the "classifier_model" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableClassifierModel(v *string) *IntentRouterCreate {
	if v != nil {
		_c.SetClassifierModel(*v)
	}
	return _c
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (_c *IntentRouterCreate) SetClassifierTimeoutMs(v int) *IntentRouterCreate {
	_c.mutation.SetClassifierTimeoutMs(v)
	return _c
}

// SetNillableClassifierTimeoutMs sets the "classifier_timeout_ms" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableClassifierTimeoutMs(v *int) *IntentRouterCreate {
	if v != nil {
		_c.SetClassifierTimeoutMs(*v)
	}
	return _c
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (_c *IntentRouterCreate) SetCacheTTLSeconds(v int) *IntentRouterCreate {
	_c.mutation.SetCacheTTLSeconds(v)
	return _c
}

// SetNillableCacheTTLSeconds sets the "cache_ttl_seconds" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableCacheTTLSeconds(v *int) *IntentRouterCreate {
	if v != nil {
		_c.SetCacheTTLSeconds(*v)
	}
	return _c
}

// SetMaxInputChars sets the "max_input_chars" field.
func (_c *IntentRouterCreate) SetMaxInputChars(v int) *IntentRouterCreate {
	_c.mutation.SetMaxInputChars(v)
	return _c
}

// SetNillableMaxInputChars sets the "max_input_chars" field if the given value is not nil.
func (_c *IntentRouterCreate) SetNillableMaxInputChars(v *int) *IntentRouterCreate {
	if v != nil {
		_c.SetMaxInputChars(*v)
	}
	return _c
}

// SetRules sets the "rules" field.
func (_c *IntentRouterCreate) SetRules(v []domain.IntentRule) *IntentRouterCreate {
	_c.mutation.SetRules(v)
	return _c
}

// Mutation returns the IntentRouterMutation object of the builder.
func (_c *IntentRouterCreate) Mutation() *IntentRouterMutation {
	return _c.mutation
}

// Save creates the IntentRouter in the database.
func (_c *IntentRouterCreate) Save(ctx context.Context) (*IntentRouter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntentRouterCreate) SaveX(ctx context.Context) *IntentRouter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntentRouterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntentRouterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntentRouterCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := intentrouter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := intentrouter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := intentrouter.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ClassifierBaseURL(); !ok {
		v := intentrouter.DefaultClassifierBaseURL
		_c.mutation.SetClassifierBaseURL(v)
	}
	if _, ok := _c.mutation.ClassifierAPIKey(); !ok {
		v := intentrouter.DefaultClassifierAPIKey
		_c.mutation.SetClassifierAPIKey(v)
	}
	if _, ok := _c.mutation.ClassifierProtocol(); !ok {
		v := intentrouter.DefaultClassifierProtocol
		_c.mutation.SetClassifierProtocol(v)
	}
	if _, ok := _c.mutation.ClassifierModel(); !ok {
		v := intentrouter.DefaultClassifierModel
		_c.mutation.SetClassifierModel(v)
	}
	if _, ok := _c.mutation.ClassifierTimeoutMs(); !ok {
		v := intentrouter.DefaultClassifierTimeoutMs
		_c.mutation.SetClassifierTimeoutMs(v)
	}
	if _, ok := _c.mutation.CacheTTLSeconds(); !ok {
		v := intentrouter.DefaultCacheTTLSeconds
		_c.mutation.SetCacheTTLSeconds(v)
	}
	if _, ok := _c.mutation.MaxInputChars(); !ok {
		v := intentrouter.DefaultMaxInputChars
		_c.mutation.SetMaxInputChars(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntentRouterCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IntentRouter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IntentRouter.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "IntentRouter.group_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "IntentRouter.enabled"`)}
	}
	if _, ok := _c.mutation.ClassifierBaseURL(); !ok {
		return &ValidationError{Name: "classifier_base_url", err: errors.New(`ent: missing required field "IntentRouter.classifier_base_url"`)}
	}
	if v, ok := _c.mutation.ClassifierBaseURL(); ok {
		if err := intentrouter.ClassifierBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "classifier_base_url", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClassifierAPIKey(); !ok {
		return &ValidationError{Name: "classifier_api_key", err: errors.New(`ent: missing required field "IntentRouter.classifier_api_key"`)}
	}
	if v, ok := _c.mutation.ClassifierAPIKey(); ok {
		if err := intentrouter.ClassifierAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "classifier_api_key", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClassifierProtocol(); !ok {
		return &ValidationError{Name: "classifier_protocol", err: errors.New(`ent: missing required field "IntentRouter.classifier_protocol"`)}
	}
	if v, ok := _c.mutation.ClassifierProtocol(); ok {
		if err := intentrouter.ClassifierProtocolValidator(v); err != nil {
			return &ValidationError{Name: "classifier_protocol", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClassifierModel(); !ok {
		return &ValidationError{Name: "classifier_model", err: errors.New(`ent: missing required field "IntentRouter.classifier_model"`)}
	}
	if v, ok := _c.mutation.ClassifierModel(); ok {
		if err := intentrouter.ClassifierModelValidator(v); err != nil {
			return &ValidationError{Name: "classifier_model", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClassifierTimeoutMs(); !ok {
		return &ValidationError{Name: "classifier_timeout_ms", err: errors.New(`ent: missing required field "IntentRouter.classifier_timeout_ms"`)}
	}
	if _, ok := _c.mutation.CacheTTLSeconds(); !ok {
		return &ValidationError{Name: "cache_ttl_seconds", err: errors.New(`ent: missing required field "IntentRouter.cache_ttl_seconds"`)}
	}
	if _, ok := _c.mutation.MaxInputChars(); !ok {
		return &ValidationError{Name: "max_input_chars", err: errors.New(`ent: missing required field "IntentRouter.max_input_chars"`)}
	}
	return nil
}

func (_c *IntentRouterCreate) sqlSave(ctx context.Context) (*IntentRouter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntentRouterCreate) createSpec() (*IntentRouter, *sqlgraph.CreateSpec) {
	var (
		_node = &IntentRouter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(intentrouter.Table, sqlgraph.NewFieldSpec(intentrouter.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(intentrouter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrouter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(intentrouter.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(intentrouter.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ClassifierBaseURL(); ok {
		_spec.SetField(intentrouter.FieldClassifierBaseURL, field.TypeString, value)
		_node.ClassifierBaseURL = value
	}
	if value, ok := _c.mutation.ClassifierAPIKey(); ok {
		_spec.SetField(intentrouter.FieldClassifierAPIKey, field.TypeString, value)
		_node.ClassifierAPIKey = value
	}
	if value, ok := _c.mutation.ClassifierProtocol(); ok {
		_spec.SetField(intentrouter.FieldClassifierProtocol, field.TypeString, value)
		_node.ClassifierProtocol = value
	}
	if value, ok := _c.mutation.ClassifierModel(); ok {
		_spec.SetField(intentrouter.FieldClassifierModel, field.TypeString, value)
		_node.ClassifierModel = value
	}
	if value, ok := _c.mutation.ClassifierTimeoutMs(); ok {
		_spec.SetField(intentrouter.FieldClassifierTimeoutMs, field.TypeInt, value)
		_node.ClassifierTimeoutMs = value
	}
	if value, ok := _c.mutation.CacheTTLSeconds(); ok {
		_spec.SetField(intentrouter.FieldCacheTTLSeconds, field.TypeInt, value)
		_node.CacheTTLSeconds = value
	}
	if value, ok := _c.mutation.MaxInputChars(); ok {
		_spec.SetField(intentrouter.FieldMaxInputChars, field.TypeInt, value)
		_node.MaxInputChars = value
	}
	if value, ok := _c.mutation.Rules(); ok {
		_spec.SetField(intentrouter.FieldRules, field.TypeJSON, value)
		_node.Rules = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntentRouter.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntentRouterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntentRouterCreate) OnConflict(opts ...sql.ConflictOption) *IntentRouterUpsertOne {
	_c.conflict = opts
	return &IntentRouterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntentRouterCreate) OnConflictColumns(columns ...string) *IntentRouterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntentRouterUpsertOne{
		create: _c,
	}
}

type (
	// IntentRouterUpsertOne is the builder for "upsert"-ing
	//  one IntentRouter node.
	IntentRouterUpsertOne struct {
		create *IntentRouterCreate
	}

	// IntentRouterUpsert is the "OnConflict" setter.
	IntentRouterUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IntentRouterUpsert) SetUpdatedAt(v time.Time) *IntentRouterUpsert {
	u.Set(intentrouter.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateUpdatedAt() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *IntentRouterUpsert) SetGroupID(v int64) *IntentRouterUpsert {
	u.Set(intentrouter.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateGroupID() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *IntentRouterUpsert) AddGroupID(v int64) *IntentRouterUpsert {
	u.Add(intentrouter.FieldGroupID, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *IntentRouterUpsert) SetEnabled(v bool) *IntentRouterUpsert {
	u.Set(intentrouter.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateEnabled() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldEnabled)
	return u
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (u *IntentRouterUpsert) SetClassifierBaseURL(v string) *IntentRouterUpsert {
	u.Set(intentrouter.FieldClassifierBaseURL, v)
	return u
}

// UpdateClassifierBaseURL sets the "classifier_base_url" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateClassifierBaseURL() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldClassifierBaseURL)
	return u
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (u *IntentRouterUpsert) SetClassifierAPIKey(v string) *IntentRouterUpsert {
	u.Set(intentrouter.FieldClassifierAPIKey, v)
	return u
}

// UpdateClassifierAPIKey sets the "classifier_api_key" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateClassifierAPIKey() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldClassifierAPIKey)
	return u
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (u *IntentRouterUpsert) SetClassifierProtocol(v string) *IntentRouterUpsert {
	u.Set(intentrouter.FieldClassifierProtocol, v)
	return u
}

// UpdateClassifierProtocol sets the "classifier_protocol" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateClassifierProtocol() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldClassifierProtocol)
	return u
}

// SetClassifierModel sets the "classifier_model" field.
func (u *IntentRouterUpsert) SetClassifierModel(v string) *IntentRouterUpsert {
	u.Set(intentrouter.FieldClassifierModel, v)
	return u
}

// UpdateClassifierModel sets the "classifier_model" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateClassifierModel() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldClassifierModel)
	return u
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (u *IntentRouterUpsert) SetClassifierTimeoutMs(v int) *IntentRouterUpsert {
	u.Set(intentrouter.FieldClassifierTimeoutMs, v)
	return u
}

// UpdateClassifierTimeoutMs sets the "classifier_timeout_ms" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateClassifierTimeoutMs() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldClassifierTimeoutMs)
	return u
}

// AddClassifierTimeoutMs adds v to the "classifier_timeout_ms" field.
func (u *IntentRouterUpsert) AddClassifierTimeoutMs(v int) *IntentRouterUpsert {
	u.Add(intentrouter.FieldClassifierTimeoutMs, v)
	return u
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (u *IntentRouterUpsert) SetCacheTTLSeconds(v int) *IntentRouterUpsert {
	u.Set(intentrouter.FieldCacheTTLSeconds, v)
	return u
}

// UpdateCacheTTLSeconds sets the "cache_ttl_seconds" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateCacheTTLSeconds() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldCacheTTLSeconds)
	return u
}

// AddCacheTTLSeconds adds v to the "cache_ttl_seconds" field.
func (u *IntentRouterUpsert) AddCacheTTLSeconds(v int) *IntentRouterUpsert {
	u.Add(intentrouter.FieldCacheTTLSeconds, v)
	return u
}

// SetMaxInputChars sets the "max_input_chars" field.
func (u *IntentRouterUpsert) SetMaxInputChars(v int) *IntentRouterUpsert {
	u.Set(intentrouter.FieldMaxInputChars, v)
	return u
}

// UpdateMaxInputChars sets the "max_input_chars" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateMaxInputChars() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldMaxInputChars)
	return u
}

// AddMaxInputChars adds v to the "max_input_chars" field.
func (u *IntentRouterUpsert) AddMaxInputChars(v int) *IntentRouterUpsert {
	u.Add(intentrouter.FieldMaxInputChars, v)
	return u
}

// SetRules sets the "rules" field.
func (u *IntentRouterUpsert) SetRules(v []domain.IntentRule) *IntentRouterUpsert {
	u.Set(intentrouter.FieldRules, v)
	return u
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *IntentRouterUpsert) UpdateRules() *IntentRouterUpsert {
	u.SetExcluded(intentrouter.FieldRules)
	return u
}

// ClearRules clears the value of the "rules" field.
func (u *IntentRouterUpsert) ClearRules() *IntentRouterUpsert {
	u.SetNull(intentrouter.FieldRules)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntentRouterUpsertOne) UpdateNewValues() *IntentRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(intentrouter.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntentRouterUpsertOne) Ignore() *IntentRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntentRouterUpsertOne) DoNothing() *IntentRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntentRouterCreate.OnConflict
// documentation for more info.
func (u *IntentRouterUpsertOne) Update(set func(*IntentRouterUpsert)) *IntentRouterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntentRouterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntentRouterUpsertOne) SetUpdatedAt(v time.Time) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateUpdatedAt() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *IntentRouterUpsertOne) SetGroupID(v int64) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *IntentRouterUpsertOne) AddGroupID(v int64) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateGroupID() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntentRouterUpsertOne) SetEnabled(v bool) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateEnabled() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateEnabled()
	})
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (u *IntentRouterUpsertOne) SetClassifierBaseURL(v string) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierBaseURL(v)
	})
}

// UpdateClassifierBaseURL sets the "classifier_base_url" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateClassifierBaseURL() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierBaseURL()
	})
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (u *IntentRouterUpsertOne) SetClassifierAPIKey(v string) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierAPIKey(v)
	})
}

// UpdateClassifierAPIKey sets the "classifier_api_key" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateClassifierAPIKey() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierAPIKey()
	})
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (u *IntentRouterUpsertOne) SetClassifierProtocol(v string) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierProtocol(v)
	})
}

// UpdateClassifierProtocol sets the "classifier_protocol" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateClassifierProtocol() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierProtocol()
	})
}

// SetClassifierModel sets the "classifier_model" field.
func (u *IntentRouterUpsertOne) SetClassifierModel(v string) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierModel(v)
	})
}

// UpdateClassifierModel sets the "classifier_model" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateClassifierModel() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierModel()
	})
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (u *IntentRouterUpsertOne) SetClassifierTimeoutMs(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierTimeoutMs(v)
	})
}

// AddClassifierTimeoutMs adds v to the "classifier_timeout_ms" field.
func (u *IntentRouterUpsertOne) AddClassifierTimeoutMs(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddClassifierTimeoutMs(v)
	})
}

// UpdateClassifierTimeoutMs sets the "classifier_timeout_ms" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateClassifierTimeoutMs() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierTimeoutMs()
	})
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (u *IntentRouterUpsertOne) SetCacheTTLSeconds(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetCacheTTLSeconds(v)
	})
}

// AddCacheTTLSeconds adds v to the "cache_ttl_seconds" field.
func (u *IntentRouterUpsertOne) AddCacheTTLSeconds(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddCacheTTLSeconds(v)
	})
}

// UpdateCacheTTLSeconds sets the "cache_ttl_seconds" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateCacheTTLSeconds() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateCacheTTLSeconds()
	})
}

// SetMaxInputChars sets the "max_input_chars" field.
func (u *IntentRouterUpsertOne) SetMaxInputChars(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetMaxInputChars(v)
	})
}

// AddMaxInputChars adds v to the "max_input_chars" field.
func (u *IntentRouterUpsertOne) AddMaxInputChars(v int) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddMaxInputChars(v)
	})
}

// UpdateMaxInputChars sets the "max_input_chars" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateMaxInputChars() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateMaxInputChars()
	})
}

// SetRules sets the "rules" field.
func (u *IntentRouterUpsertOne) SetRules(v []domain.IntentRule) *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetRules(v)
	})
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *IntentRouterUpsertOne) UpdateRules() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateRules()
	})
}

// ClearRules clears the value of the "rules" field.
func (u *IntentRouterUpsertOne) ClearRules() *IntentRouterUpsertOne {
	return u.Update(func(s *IntentRouterUpsert) {
		s.ClearRules()
	})
}

// Exec executes the query.
func (u *IntentRouterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntentRouterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntentRouterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntentRouterUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntentRouterUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntentRouterCreateBulk is the builder for creating many IntentRouter entities in bulk.
type IntentRouterCreateBulk struct {
	config
	err      error
	builders []*IntentRouterCreate
	conflict []sql.ConflictOption
}

// Save creates the IntentRouter entities in the database.
func (_c *IntentRouterCreateBulk) Save(ctx context.Context) ([]*IntentRouter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntentRouter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntentRouterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntentRouterCreateBulk) SaveX(ctx context.Context) []*IntentRouter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntentRouterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntentRouterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntentRouter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntentRouterUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntentRouterCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntentRouterUpsertBulk {
	_c.conflict = opts
	return &IntentRouterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntentRouterCreateBulk) OnConflictColumns(columns ...string) *IntentRouterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntentRouterUpsertBulk{
		create: _c,
	}
}

// IntentRouterUpsertBulk is the builder for "upsert"-ing
// a bulk of IntentRouter nodes.
type IntentRouterUpsertBulk struct {
	create *IntentRouterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntentRouterUpsertBulk) UpdateNewValues() *IntentRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(intentrouter.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntentRouter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntentRouterUpsertBulk) Ignore() *IntentRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntentRouterUpsertBulk) DoNothing() *IntentRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntentRouterCreateBulk.OnConflict
// documentation for more info.
func (u *IntentRouterUpsertBulk) Update(set func(*IntentRouterUpsert)) *IntentRouterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntentRouterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntentRouterUpsertBulk) SetUpdatedAt(v time.Time) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateUpdatedAt() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *IntentRouterUpsertBulk) SetGroupID(v int64) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *IntentRouterUpsertBulk) AddGroupID(v int64) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateGroupID() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntentRouterUpsertBulk) SetEnabled(v bool) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateEnabled() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateEnabled()
	})
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (u *IntentRouterUpsertBulk) SetClassifierBaseURL(v string) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierBaseURL(v)
	})
}

// UpdateClassifierBaseURL sets the "classifier_base_url" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateClassifierBaseURL() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierBaseURL()
	})
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (u *IntentRouterUpsertBulk) SetClassifierAPIKey(v string) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierAPIKey(v)
	})
}

// UpdateClassifierAPIKey sets the "classifier_api_key" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateClassifierAPIKey() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierAPIKey()
	})
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (u *IntentRouterUpsertBulk) SetClassifierProtocol(v string) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierProtocol(v)
	})
}

// UpdateClassifierProtocol sets the "classifier_protocol" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateClassifierProtocol() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierProtocol()
	})
}

// SetClassifierModel sets the "classifier_model" field.
func (u *IntentRouterUpsertBulk) SetClassifierModel(v string) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierModel(v)
	})
}

// UpdateClassifierModel sets the "classifier_model" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateClassifierModel() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierModel()
	})
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (u *IntentRouterUpsertBulk) SetClassifierTimeoutMs(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetClassifierTimeoutMs(v)
	})
}

// AddClassifierTimeoutMs adds v to the "classifier_timeout_ms" field.
func (u *IntentRouterUpsertBulk) AddClassifierTimeoutMs(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddClassifierTimeoutMs(v)
	})
}

// UpdateClassifierTimeoutMs sets the "classifier_timeout_ms" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateClassifierTimeoutMs() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateClassifierTimeoutMs()
	})
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (u *IntentRouterUpsertBulk) SetCacheTTLSeconds(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetCacheTTLSeconds(v)
	})
}

// AddCacheTTLSeconds adds v to the "cache_ttl_seconds" field.
func (u *IntentRouterUpsertBulk) AddCacheTTLSeconds(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddCacheTTLSeconds(v)
	})
}

// UpdateCacheTTLSeconds sets the "cache_ttl_seconds" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateCacheTTLSeconds() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateCacheTTLSeconds()
	})
}

// SetMaxInputChars sets the "max_input_chars" field.
func (u *IntentRouterUpsertBulk) SetMaxInputChars(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetMaxInputChars(v)
	})
}

// AddMaxInputChars adds v to the "max_input_chars" field.
func (u *IntentRouterUpsertBulk) AddMaxInputChars(v int) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.AddMaxInputChars(v)
	})
}

// UpdateMaxInputChars sets the "max_input_chars" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateMaxInputChars() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateMaxInputChars()
	})
}

// SetRules sets the "rules" field.
func (u *IntentRouterUpsertBulk) SetRules(v []domain.IntentRule) *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.SetRules(v)
	})
}

// UpdateRules sets the "rules" field to the value that was provided on create.
func (u *IntentRouterUpsertBulk) UpdateRules() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.UpdateRules()
	})
}

// ClearRules clears the value of the "rules" field.
func (u *IntentRouterUpsertBulk) ClearRules() *IntentRouterUpsertBulk {
	return u.Update(func(s *IntentRouterUpsert) {
		s.ClearRules()
	})
}

// Exec executes the query.
func (u *IntentRouterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntentRouterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntentRouterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntentRouterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
