// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/intentrouter"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// IntentRouter is the model entity for the IntentRouter schema.
type IntentRouter struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ClassifierBaseURL holds the value of the "classifier_base_url" field.
	ClassifierBaseURL string `json:"classifier_base_url,omitempty"`
	// ClassifierAPIKey holds the value of the "classifier_api_key" field.
	ClassifierAPIKey string `json:"-"`
	// ClassifierProtocol holds the value of the "classifier_protocol" field.
	ClassifierProtocol string `json:"classifier_protocol,omitempty"`
	// ClassifierModel holds the value of the "classifier_model" field.
	ClassifierModel string `json:"classifier_model,omitempty"`
	// ClassifierTimeoutMs holds the value of the "classifier_timeout_ms" field.
	ClassifierTimeoutMs int `json:"classifier_timeout_ms,omitempty"`
	// CacheTTLSeconds holds the value of the "cache_ttl_seconds" field.
	CacheTTLSeconds int `json:"cache_ttl_seconds,omitempty"`
	// MaxInputChars holds the value of the "max_input_chars" field.
	MaxInputChars int `json:"max_input_chars,omitempty"`
	// Rules holds the value of the "rules" field.
	Rules        []domain.IntentRule `json:"rules,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntentRouter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intentrouter.FieldRules:
			values[i] = new([]byte)
		case intentrouter.FieldEnabled:
			values[i] = new(sql.NullBool)
		case intentrouter.FieldID, intentrouter.FieldGroupID, intentrouter.FieldClassifierTimeoutMs, intentrouter.FieldCacheTTLSeconds, intentrouter.FieldMaxInputChars:
			values[i] = new(sql.NullInt64)
		case intentrouter.FieldClassifierBaseURL, intentrouter.FieldClassifierAPIKey, intentrouter.FieldClassifierProtocol, intentrouter.FieldClassifierModel:
			values[i] = new(sql.NullString)
		case intentrouter.FieldCreatedAt, intentrouter.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntentRouter fields.
func (_m *IntentRouter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intentrouter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case intentrouter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intentrouter.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case intentrouter.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case intentrouter.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case intentrouter.FieldClassifierBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_base_url", values[i])
			} else if value.Valid {
				_m.ClassifierBaseURL = value.String
			}
		case intentrouter.FieldClassifierAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_api_key", values[i])
			} else if value.Valid {
				_m.ClassifierAPIKey = value.String
			}
		case intentrouter.FieldClassifierProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_protocol", values[i])
			} else if value.Valid {
				_m.ClassifierProtocol = value.String
			}
		case intentrouter.FieldClassifierModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_model", values[i])
			} else if value.Valid {
				_m.ClassifierModel = value.String
			}
		case intentrouter.FieldClassifierTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field classifier_timeout_ms", values[i])
			} else if value.Valid {
				_m.ClassifierTimeoutMs = int(value.Int64)
			}
		case intentrouter.FieldCacheTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_ttl_seconds", values[i])
			} else if value.Valid {
				_m.CacheTTLSeconds = int(value.Int64)
			}
		case intentrouter.FieldMaxInputChars:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_input_chars", values[i])
			} else if value.Valid {
				_m.MaxInputChars = int(value.Int64)
			}
		case intentrouter.FieldRules:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rules", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Rules); err != nil {
					return fmt.Errorf("unmarshal field rules: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntentRouter.
// This includes values selected through modifiers, order, etc.
func (_m *IntentRouter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntentRouter.
// Note that you need to call IntentRouter.Unwrap() before calling this method if this IntentRouter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntentRouter) Update() *IntentRouterUpdateOne {
	return NewIntentRouterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntentRouter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntentRouter) Unwrap() *IntentRouter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntentRouter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntentRouter) String() string {
	var builder strings.Builder
	builder.WriteString("IntentRouter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("classifier_base_url=")
	builder.WriteString(_m.ClassifierBaseURL)
	builder.WriteString(", ")
	builder.WriteString("classifier_api_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("classifier_protocol=")
	builder.WriteString(_m.ClassifierProtocol)
	builder.WriteString(", ")
	builder.WriteString("classifier_model=")
	builder.WriteString(_m.ClassifierModel)
	builder.WriteString(", ")
	builder.WriteString("classifier_timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassifierTimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("cache_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("max_input_chars=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxInputChars))
	builder.WriteString(", ")
	builder.WriteString("rules=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rules))
	builder.WriteByte(')')
	return builder.String()
}

// IntentRouters is a parsable slice of IntentRouter.
type IntentRouters []*IntentRouter
