// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/intentrouter"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// IntentRouterUpdate is the builder for updating IntentRouter entities.
type IntentRouterUpdate struct {
	config
	hooks    []Hook
	mutation *IntentRouterMutation
}

// Where appends a list predicates to the IntentRouterUpdate builder.
func (_u *IntentRouterUpdate) Where(ps ...predicate.IntentRouter) *IntentRouterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntentRouterUpdate) SetUpdatedAt(v time.Time) *IntentRouterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *IntentRouterUpdate) SetGroupID(v int64) *IntentRouterUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableGroupID(v *int64) *IntentRouterUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *IntentRouterUpdate) AddGroupID(v int64) *IntentRouterUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntentRouterUpdate) SetEnabled(v bool) *IntentRouterUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableEnabled(v *bool) *IntentRouterUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (_u *IntentRouterUpdate) SetClassifierBaseURL(v string) *IntentRouterUpdate {
	_u.mutation.SetClassifierBaseURL(v)
	return _u
}

// SetNillableClassifierBaseURL sets the "classifier_base_url" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableClassifierBaseURL(v *string) *IntentRouterUpdate {
	if v != nil {
		_u.SetClassifierBaseURL(*v)
	}
	return _u
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (_u *IntentRouterUpdate) SetClassifierAPIKey(v string) *IntentRouterUpdate {
	_u.mutation.SetClassifierAPIKey(v)
	return _u
}

// SetNillableClassifierAPIKey sets the "classifier_api_key" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableClassifierAPIKey(v *string) *IntentRouterUpdate {
	if v != nil {
		_u.SetClassifierAPIKey(*v)
	}
	return _u
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (_u *IntentRouterUpdate) SetClassifierProtocol(v string) *IntentRouterUpdate {
	_u.mutation.SetClassifierProtocol(v)
	return _u
}

// SetNillableClassifierProtocol sets the "classifier_protocol" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableClassifierProtocol(v *string) *IntentRouterUpdate {
	if v != nil {
		_u.SetClassifierProtocol(*v)
	}
	return _u
}

// SetClassifierModel sets the "classifier_model" field.
func (_u *IntentRouterUpdate) SetClassifierModel(v string) *IntentRouterUpdate {
	_u.mutation.SetClassifierModel(v)
	return _u
}

// SetNillableClassifierModel sets the "classifier_model" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableClassifierModel(v *string) *IntentRouterUpdate {
	if v != nil {
		_u.SetClassifierModel(*v)
	}
	return _u
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (_u *IntentRouterUpdate) SetClassifierTimeoutMs(v int) *IntentRouterUpdate {
	_u.mutation.ResetClassifierTimeoutMs()
	_u.mutation.SetClassifierTimeoutMs(v)
	return _u
}

// SetNillableClassifierTimeoutMs sets the "classifier_timeout_ms" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableClassifierTimeoutMs(v *int) *IntentRouterUpdate {
	if v != nil {
		_u.SetClassifierTimeoutMs(*v)
	}
	return _u
}

// AddClassifierTimeoutMs adds value to the "classifier_timeout_ms" field.
func (_u *IntentRouterUpdate) AddClassifierTimeoutMs(v int) *IntentRouterUpdate {
	_u.mutation.AddClassifierTimeoutMs(v)
	return _u
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (_u *IntentRouterUpdate) SetCacheTTLSeconds(v int) *IntentRouterUpdate {
	_u.mutation.ResetCacheTTLSeconds()
	_u.mutation.SetCacheTTLSeconds(v)
	return _u
}

// SetNillableCacheTTLSeconds sets the "cache_ttl_seconds" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableCacheTTLSeconds(v *int) *IntentRouterUpdate {
	if v != nil {
		_u.SetCacheTTLSeconds(*v)
	}
	return _u
}

// AddCacheTTLSeconds adds value to the "cache_ttl_seconds" field.
func (_u *IntentRouterUpdate) AddCacheTTLSeconds(v int) *IntentRouterUpdate {
	_u.mutation.AddCacheTTLSeconds(v)
	return _u
}

// SetMaxInputChars sets the "max_input_chars" field.
func (_u *IntentRouterUpdate) SetMaxInputChars(v int) *IntentRouterUpdate {
	_u.mutation.ResetMaxInputChars()
	_u.mutation.SetMaxInputChars(v)
	return _u
}

// SetNillableMaxInputChars sets the "max_input_chars" field if the given value is not nil.
func (_u *IntentRouterUpdate) SetNillableMaxInputChars(v *int) *IntentRouterUpdate {
	if v != nil {
		_u.SetMaxInputChars(*v)
	}
	return _u
}

// AddMaxInputChars adds value to the "max_input_chars" field.
func (_u *IntentRouterUpdate) AddMaxInputChars(v int) *IntentRouterUpdate {
	_u.mutation.AddMaxInputChars(v)
	return _u
}

// SetRules sets the "rules" field.
func (_u *IntentRouterUpdate) SetRules(v []domain.IntentRule) *IntentRouterUpdate {
	_u.mutation.SetRules(v)
	return _u
}

// AppendRules appends value to the "rules" field.
func (_u *IntentRouterUpdate) AppendRules(v []domain.IntentRule) *IntentRouterUpdate {
	_u.mutation.AppendRules(v)
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *IntentRouterUpdate) ClearRules() *IntentRouterUpdate {
	_u.mutation.ClearRules()
	return _u
}

// Mutation returns the IntentRouterMutation object of the builder.
func (_u *IntentRouterUpdate) Mutation() *IntentRouterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntentRouterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntentRouterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntentRouterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntentRouterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntentRouterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intentrouter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntentRouterUpdate) check() error {
	if v, ok := _u.mutation.ClassifierBaseURL(); ok {
		if err := intentrouter.ClassifierBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "classifier_base_url", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierAPIKey(); ok {
		if err := intentrouter.ClassifierAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "classifier_api_key", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierProtocol(); ok {
		if err := intentrouter.ClassifierProtocolValidator(v); err != nil {
			return &ValidationError{Name: "classifier_protocol", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierModel(); ok {
		if err := intentrouter.ClassifierModelValidator(v); err != nil {
			return &ValidationError{Name: "classifier_model", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_model": %w`, err)}
		}
	}
	return nil
}

func (_u *IntentRouterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intentrouter.Table, intentrouter.Columns, sqlgraph.NewFieldSpec(intentrouter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrouter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(intentrouter.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(intentrouter.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(intentrouter.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClassifierBaseURL(); ok {
		_spec.SetField(intentrouter.FieldClassifierBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierAPIKey(); ok {
		_spec.SetField(intentrouter.FieldClassifierAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierProtocol(); ok {
		_spec.SetField(intentrouter.FieldClassifierProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierModel(); ok {
		_spec.SetField(intentrouter.FieldClassifierModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierTimeoutMs(); ok {
		_spec.SetField(intentrouter.FieldClassifierTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassifierTimeoutMs(); ok {
		_spec.AddField(intentrouter.FieldClassifierTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheTTLSeconds(); ok {
		_spec.SetField(intentrouter.FieldCacheTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheTTLSeconds(); ok {
		_spec.AddField(intentrouter.FieldCacheTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxInputChars(); ok {
		_spec.SetField(intentrouter.FieldMaxInputChars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxInputChars(); ok {
		_spec.AddField(intentrouter.FieldMaxInputChars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(intentrouter.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intentrouter.FieldRules, value)
		})
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(intentrouter.FieldRules, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intentrouter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntentRouterUpdateOne is the builder for updating a single IntentRouter entity.
type IntentRouterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntentRouterMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntentRouterUpdateOne) SetUpdatedAt(v time.Time) *IntentRouterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *IntentRouterUpdateOne) SetGroupID(v int64) *IntentRouterUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableGroupID(v *int64) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *IntentRouterUpdateOne) AddGroupID(v int64) *IntentRouterUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntentRouterUpdateOne) SetEnabled(v bool) *IntentRouterUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableEnabled(v *bool) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetClassifierBaseURL sets the "classifier_base_url" field.
func (_u *IntentRouterUpdateOne) SetClassifierBaseURL(v string) *IntentRouterUpdateOne {
	_u.mutation.SetClassifierBaseURL(v)
	return _u
}

// SetNillableClassifierBaseURL sets the "classifier_base_url" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableClassifierBaseURL(v *string) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetClassifierBaseURL(*v)
	}
	return _u
}

// SetClassifierAPIKey sets the "classifier_api_key" field.
func (_u *IntentRouterUpdateOne) SetClassifierAPIKey(v string) *IntentRouterUpdateOne {
	_u.mutation.SetClassifierAPIKey(v)
	return _u
}

// SetNillableClassifierAPIKey sets the "classifier_api_key" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableClassifierAPIKey(v *string) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetClassifierAPIKey(*v)
	}
	return _u
}

// SetClassifierProtocol sets the "classifier_protocol" field.
func (_u *IntentRouterUpdateOne) SetClassifierProtocol(v string) *IntentRouterUpdateOne {
	_u.mutation.SetClassifierProtocol(v)
	return _u
}

// SetNillableClassifierProtocol sets the "classifier_protocol" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableClassifierProtocol(v *string) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetClassifierProtocol(*v)
	}
	return _u
}

// SetClassifierModel sets the "classifier_model" field.
func (_u *IntentRouterUpdateOne) SetClassifierModel(v string) *IntentRouterUpdateOne {
	_u.mutation.SetClassifierModel(v)
	return _u
}

// SetNillableClassifierModel sets the "classifier_model" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableClassifierModel(v *string) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetClassifierModel(*v)
	}
	return _u
}

// SetClassifierTimeoutMs sets the "classifier_timeout_ms" field.
func (_u *IntentRouterUpdateOne) SetClassifierTimeoutMs(v int) *IntentRouterUpdateOne {
	_u.mutation.ResetClassifierTimeoutMs()
	_u.mutation.SetClassifierTimeoutMs(v)
	return _u
}

// SetNillableClassifierTimeoutMs sets the "classifier_timeout_ms" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableClassifierTimeoutMs(v *int) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetClassifierTimeoutMs(*v)
	}
	return _u
}

// AddClassifierTimeoutMs adds value to the "classifier_timeout_ms" field.
func (_u *IntentRouterUpdateOne) AddClassifierTimeoutMs(v int) *IntentRouterUpdateOne {
	_u.mutation.AddClassifierTimeoutMs(v)
	return _u
}

// SetCacheTTLSeconds sets the "cache_ttl_seconds" field.
func (_u *IntentRouterUpdateOne) SetCacheTTLSeconds(v int) *IntentRouterUpdateOne {
	_u.mutation.ResetCacheTTLSeconds()
	_u.mutation.SetCacheTTLSeconds(v)
	return _u
}

// SetNillableCacheTTLSeconds sets the "cache_ttl_seconds" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableCacheTTLSeconds(v *int) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetCacheTTLSeconds(*v)
	}
	return _u
}

// AddCacheTTLSeconds adds value to the "cache_ttl_seconds" field.
func (_u *IntentRouterUpdateOne) AddCacheTTLSeconds(v int) *IntentRouterUpdateOne {
	_u.mutation.AddCacheTTLSeconds(v)
	return _u
}

// SetMaxInputChars sets the "max_input_chars" field.
func (_u *IntentRouterUpdateOne) SetMaxInputChars(v int) *IntentRouterUpdateOne {
	_u.mutation.ResetMaxInputChars()
	_u.mutation.SetMaxInputChars(v)
	return _u
}

// SetNillableMaxInputChars sets the "max_input_chars" field if the given value is not nil.
func (_u *IntentRouterUpdateOne) SetNillableMaxInputChars(v *int) *IntentRouterUpdateOne {
	if v != nil {
		_u.SetMaxInputChars(*v)
	}
	return _u
}

// AddMaxInputChars adds value to the "max_input_chars" field.
func (_u *IntentRouterUpdateOne) AddMaxInputChars(v int) *IntentRouterUpdateOne {
	_u.mutation.AddMaxInputChars(v)
	return _u
}

// SetRules sets the "rules" field.
func (_u *IntentRouterUpdateOne) SetRules(v []domain.IntentRule) *IntentRouterUpdateOne {
	_u.mutation.SetRules(v)
	return _u
}

// AppendRules appends value to the "rules" field.
func (_u *IntentRouterUpdateOne) AppendRules(v []domain.IntentRule) *IntentRouterUpdateOne {
	_u.mutation.AppendRules(v)
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *IntentRouterUpdateOne) ClearRules() *IntentRouterUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// Mutation returns the IntentRouterMutation object of the builder.
func (_u *IntentRouterUpdateOne) Mutation() *IntentRouterMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntentRouterUpdate builder.
func (_u *IntentRouterUpdateOne) Where(ps ...predicate.IntentRouter) *IntentRouterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntentRouterUpdateOne) Select(field string, fields ...string) *IntentRouterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntentRouter entity.
func (_u *IntentRouterUpdateOne) Save(ctx context.Context) (*IntentRouter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntentRouterUpdateOne) SaveX(ctx context.Context) *IntentRouter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntentRouterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntentRouterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntentRouterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intentrouter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntentRouterUpdateOne) check() error {
	if v, ok := _u.mutation.ClassifierBaseURL(); ok {
		if err := intentrouter.ClassifierBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "classifier_base_url", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierAPIKey(); ok {
		if err := intentrouter.ClassifierAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "classifier_api_key", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierProtocol(); ok {
		if err := intentrouter.ClassifierProtocolValidator(v); err != nil {
			return &ValidationError{Name: "classifier_protocol", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClassifierModel(); ok {
		if err := intentrouter.ClassifierModelValidator(v); err != nil {
			return &ValidationError{Name: "classifier_model", err: fmt.Errorf(`ent: validator failed for field "IntentRouter.classifier_model": %w`, err)}
		}
	}
	return nil
}

func (_u *IntentRouterUpdateOne) sqlSave(ctx context.Context) (_node *IntentRouter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intentrouter.Table, intentrouter.Columns, sqlgraph.NewFieldSpec(intentrouter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntentRouter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, intentrouter.FieldID)
		for _, f := range fields {
			if !intentrouter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != intentrouter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrouter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(intentrouter.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(intentrouter.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(intentrouter.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClassifierBaseURL(); ok {
		_spec.SetField(intentrouter.FieldClassifierBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierAPIKey(); ok {
		_spec.SetField(intentrouter.FieldClassifierAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierProtocol(); ok {
		_spec.SetField(intentrouter.FieldClassifierProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierModel(); ok {
		_spec.SetField(intentrouter.FieldClassifierModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClassifierTimeoutMs(); ok {
		_spec.SetField(intentrouter.FieldClassifierTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassifierTimeoutMs(); ok {
		_spec.AddField(intentrouter.FieldClassifierTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheTTLSeconds(); ok {
		_spec.SetField(intentrouter.FieldCacheTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCacheTTLSeconds(); ok {
		_spec.AddField(intentrouter.FieldCacheTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxInputChars(); ok {
		_spec.SetField(intentrouter.FieldMaxInputChars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxInputChars(); ok {
		_spec.AddField(intentrouter.FieldMaxInputChars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(intentrouter.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intentrouter.FieldRules, value)
		})
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(intentrouter.FieldRules, field.TypeJSON)
	}
	_node = &IntentRouter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intentrouter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
