// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymenttransactionclaim"
)

// PaymentTransactionClaim is the model entity for the PaymentTransactionClaim schema.
type PaymentTransactionClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// TransferTime holds the value of the "transfer_time" field.
	TransferTime *time.Time `json:"transfer_time,omitempty"`
	// OrderCreatedAt holds the value of the "order_created_at" field.
	OrderCreatedAt *time.Time `json:"order_created_at,omitempty"`
	// OrderWindowEnd holds the value of the "order_window_end" field.
	OrderWindowEnd *time.Time `json:"order_window_end,omitempty"`
	// ReviewPending holds the value of the "review_pending" field.
	ReviewPending bool `json:"review_pending,omitempty"`
	// Evidence holds the value of the "evidence" field.
	Evidence map[string]interface{} `json:"evidence,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentTransactionClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymenttransactionclaim.FieldEvidence:
			values[i] = new([]byte)
		case paymenttransactionclaim.FieldReviewPending:
			values[i] = new(sql.NullBool)
		case paymenttransactionclaim.FieldID, paymenttransactionclaim.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case paymenttransactionclaim.FieldTxHash, paymenttransactionclaim.FieldSource:
			values[i] = new(sql.NullString)
		case paymenttransactionclaim.FieldTransferTime, paymenttransactionclaim.FieldOrderCreatedAt, paymenttransactionclaim.FieldOrderWindowEnd, paymenttransactionclaim.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentTransactionClaim fields.
func (_m *PaymentTransactionClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymenttransactionclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymenttransactionclaim.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case paymenttransactionclaim.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case paymenttransactionclaim.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case paymenttransactionclaim.FieldTransferTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_time", values[i])
			} else if value.Valid {
				_m.TransferTime = new(time.Time)
				*_m.TransferTime = value.Time
			}
		case paymenttransactionclaim.FieldOrderCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field order_created_at", values[i])
			} else if value.Valid {
				_m.OrderCreatedAt = new(time.Time)
				*_m.OrderCreatedAt = value.Time
			}
		case paymenttransactionclaim.FieldOrderWindowEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field order_window_end", values[i])
			} else if value.Valid {
				_m.OrderWindowEnd = new(time.Time)
				*_m.OrderWindowEnd = value.Time
			}
		case paymenttransactionclaim.FieldReviewPending:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field review_pending", values[i])
			} else if value.Valid {
				_m.ReviewPending = value.Bool
			}
		case paymenttransactionclaim.FieldEvidence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field evidence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Evidence); err != nil {
					return fmt.Errorf("unmarshal field evidence: %w", err)
				}
			}
		case paymenttransactionclaim.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentTransactionClaim.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentTransactionClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentTransactionClaim.
// Note that you need to call PaymentTransactionClaim.Unwrap() before calling this method if this PaymentTransactionClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentTransactionClaim) Update() *PaymentTransactionClaimUpdateOne {
	return NewPaymentTransactionClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentTransactionClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentTransactionClaim) Unwrap() *PaymentTransactionClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentTransactionClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentTransactionClaim) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentTransactionClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.TransferTime; v != nil {
		builder.WriteString("transfer_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OrderCreatedAt; v != nil {
		builder.WriteString("order_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OrderWindowEnd; v != nil {
		builder.WriteString("order_window_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("review_pending=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewPending))
	builder.WriteString(", ")
	builder.WriteString("evidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Evidence))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentTransactionClaims is a parsable slice of PaymentTransactionClaim.
type PaymentTransactionClaims []*PaymentTransactionClaim
