// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymenttransactionclaim"
)

// PaymentTransactionClaimCreate is the builder for creating a PaymentTransactionClaim entity.
type PaymentTransactionClaimCreate struct {
	config
	mutation *PaymentTransactionClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTxHash sets the "tx_hash" field.
func (_c *PaymentTransactionClaimCreate) SetTxHash(v string) *PaymentTransactionClaimCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *PaymentTransactionClaimCreate) SetOrderID(v int64) *PaymentTransactionClaimCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentTransactionClaimCreate) SetCreatedAt(v time.Time) *PaymentTransactionClaimCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentTransactionClaimCreate) SetNillableCreatedAt(v *time.Time) *PaymentTransactionClaimCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentTransactionClaimMutation object of the builder.
func (_c *PaymentTransactionClaimCreate) Mutation() *PaymentTransactionClaimMutation {
	return _c.mutation
}

// Save creates the PaymentTransactionClaim in the database.
func (_c *PaymentTransactionClaimCreate) Save(ctx context.Context) (*PaymentTransactionClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentTransactionClaimCreate) SaveX(ctx context.Context) *PaymentTransactionClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentTransactionClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentTransactionClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentTransactionClaimCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymenttransactionclaim.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentTransactionClaimCreate) check() error {
	if _, ok := _c.mutation.TxHash(); !ok {
		return &ValidationError{Name: "tx_hash", err: errors.New(`ent: missing required field "PaymentTransactionClaim.tx_hash"`)}
	}
	if v, ok := _c.mutation.TxHash(); ok {
		if err := paymenttransactionclaim.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentTransactionClaim.tx_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "PaymentTransactionClaim.order_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentTransactionClaim.created_at"`)}
	}
	return nil
}

func (_c *PaymentTransactionClaimCreate) sqlSave(ctx context.Context) (*PaymentTransactionClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentTransactionClaimCreate) createSpec() (*PaymentTransactionClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentTransactionClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymenttransactionclaim.Table, sqlgraph.NewFieldSpec(paymenttransactionclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(paymenttransactionclaim.FieldTxHash, field.TypeString, value)
		_node.TxHash = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(paymenttransactionclaim.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymenttransactionclaim.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentTransactionClaim.Create().
//		SetTxHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentTransactionClaimUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentTransactionClaimCreate) OnConflict(opts ...sql.ConflictOption) *PaymentTransactionClaimUpsertOne {
	_c.conflict = opts
	return &PaymentTransactionClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentTransactionClaimCreate) OnConflictColumns(columns ...string) *PaymentTransactionClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentTransactionClaimUpsertOne{
		create: _c,
	}
}

type (
	// PaymentTransactionClaimUpsertOne is the builder for "upsert"-ing
	//  one PaymentTransactionClaim node.
	PaymentTransactionClaimUpsertOne struct {
		create *PaymentTransactionClaimCreate
	}

	// PaymentTransactionClaimUpsert is the "OnConflict" setter.
	PaymentTransactionClaimUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentTransactionClaimUpsertOne) UpdateNewValues() *PaymentTransactionClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TxHash(); exists {
			s.SetIgnore(paymenttransactionclaim.FieldTxHash)
		}
		if _, exists := u.create.mutation.OrderID(); exists {
			s.SetIgnore(paymenttransactionclaim.FieldOrderID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymenttransactionclaim.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentTransactionClaimUpsertOne) Ignore() *PaymentTransactionClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentTransactionClaimUpsertOne) DoNothing() *PaymentTransactionClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentTransactionClaimCreate.OnConflict
// documentation for more info.
func (u *PaymentTransactionClaimUpsertOne) Update(set func(*PaymentTransactionClaimUpsert)) *PaymentTransactionClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentTransactionClaimUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *PaymentTransactionClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentTransactionClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentTransactionClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentTransactionClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentTransactionClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentTransactionClaimCreateBulk is the builder for creating many PaymentTransactionClaim entities in bulk.
type PaymentTransactionClaimCreateBulk struct {
	config
	err      error
	builders []*PaymentTransactionClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentTransactionClaim entities in the database.
func (_c *PaymentTransactionClaimCreateBulk) Save(ctx context.Context) ([]*PaymentTransactionClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentTransactionClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentTransactionClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentTransactionClaimCreateBulk) SaveX(ctx context.Context) []*PaymentTransactionClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentTransactionClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentTransactionClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentTransactionClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentTransactionClaimUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentTransactionClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentTransactionClaimUpsertBulk {
	_c.conflict = opts
	return &PaymentTransactionClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentTransactionClaimCreateBulk) OnConflictColumns(columns ...string) *PaymentTransactionClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentTransactionClaimUpsertBulk{
		create: _c,
	}
}

// PaymentTransactionClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentTransactionClaim nodes.
type PaymentTransactionClaimUpsertBulk struct {
	create *PaymentTransactionClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentTransactionClaimUpsertBulk) UpdateNewValues() *PaymentTransactionClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TxHash(); exists {
				s.SetIgnore(paymenttransactionclaim.FieldTxHash)
			}
			if _, exists := b.mutation.OrderID(); exists {
				s.SetIgnore(paymenttransactionclaim.FieldOrderID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymenttransactionclaim.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentTransactionClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentTransactionClaimUpsertBulk) Ignore() *PaymentTransactionClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentTransactionClaimUpsertBulk) DoNothing() *PaymentTransactionClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentTransactionClaimCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentTransactionClaimUpsertBulk) Update(set func(*PaymentTransactionClaimUpsert)) *PaymentTransactionClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentTransactionClaimUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *PaymentTransactionClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentTransactionClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentTransactionClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentTransactionClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
