// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymenttransactionclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentTransactionClaimDelete is the builder for deleting a PaymentTransactionClaim entity.
type PaymentTransactionClaimDelete struct {
	config
	hooks    []Hook
	mutation *PaymentTransactionClaimMutation
}

// Where appends a list predicates to the PaymentTransactionClaimDelete builder.
func (_d *PaymentTransactionClaimDelete) Where(ps ...predicate.PaymentTransactionClaim) *PaymentTransactionClaimDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentTransactionClaimDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentTransactionClaimDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentTransactionClaimDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymenttransactionclaim.Table, sqlgraph.NewFieldSpec(paymenttransactionclaim.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentTransactionClaimDeleteOne is the builder for deleting a single PaymentTransactionClaim entity.
type PaymentTransactionClaimDeleteOne struct {
	_d *PaymentTransactionClaimDelete
}

// Where appends a list predicates to the PaymentTransactionClaimDelete builder.
func (_d *PaymentTransactionClaimDeleteOne) Where(ps ...predicate.PaymentTransactionClaim) *PaymentTransactionClaimDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentTransactionClaimDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymenttransactionclaim.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentTransactionClaimDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
