// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymenttransactionclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentTransactionClaimUpdate is the builder for updating PaymentTransactionClaim entities.
type PaymentTransactionClaimUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentTransactionClaimMutation
}

// Where appends a list predicates to the PaymentTransactionClaimUpdate builder.
func (_u *PaymentTransactionClaimUpdate) Where(ps ...predicate.PaymentTransactionClaim) *PaymentTransactionClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *PaymentTransactionClaimUpdate) SetSource(v string) *PaymentTransactionClaimUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdate) SetNillableSource(v *string) *PaymentTransactionClaimUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTransferTime sets the "transfer_time" field.
func (_u *PaymentTransactionClaimUpdate) SetTransferTime(v time.Time) *PaymentTransactionClaimUpdate {
	_u.mutation.SetTransferTime(v)
	return _u
}

// SetNillableTransferTime sets the "transfer_time" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdate) SetNillableTransferTime(v *time.Time) *PaymentTransactionClaimUpdate {
	if v != nil {
		_u.SetTransferTime(*v)
	}
	return _u
}

// ClearTransferTime clears the value of the "transfer_time" field.
func (_u *PaymentTransactionClaimUpdate) ClearTransferTime() *PaymentTransactionClaimUpdate {
	_u.mutation.ClearTransferTime()
	return _u
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (_u *PaymentTransactionClaimUpdate) SetOrderCreatedAt(v time.Time) *PaymentTransactionClaimUpdate {
	_u.mutation.SetOrderCreatedAt(v)
	return _u
}

// SetNillableOrderCreatedAt sets the "order_created_at" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdate) SetNillableOrderCreatedAt(v *time.Time) *PaymentTransactionClaimUpdate {
	if v != nil {
		_u.SetOrderCreatedAt(*v)
	}
	return _u
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (_u *PaymentTransactionClaimUpdate) ClearOrderCreatedAt() *PaymentTransactionClaimUpdate {
	_u.mutation.ClearOrderCreatedAt()
	return _u
}

// SetOrderWindowEnd sets the "order_window_end" field.
func (_u *PaymentTransactionClaimUpdate) SetOrderWindowEnd(v time.Time) *PaymentTransactionClaimUpdate {
	_u.mutation.SetOrderWindowEnd(v)
	return _u
}

// SetNillableOrderWindowEnd sets the "order_window_end" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdate) SetNillableOrderWindowEnd(v *time.Time) *PaymentTransactionClaimUpdate {
	if v != nil {
		_u.SetOrderWindowEnd(*v)
	}
	return _u
}

// ClearOrderWindowEnd clears the value of the "order_window_end" field.
func (_u *PaymentTransactionClaimUpdate) ClearOrderWindowEnd() *PaymentTransactionClaimUpdate {
	_u.mutation.ClearOrderWindowEnd()
	return _u
}

// SetReviewPending sets the "review_pending" field.
func (_u *PaymentTransactionClaimUpdate) SetReviewPending(v bool) *PaymentTransactionClaimUpdate {
	_u.mutation.SetReviewPending(v)
	return _u
}

// SetNillableReviewPending sets the "review_pending" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdate) SetNillableReviewPending(v *bool) *PaymentTransactionClaimUpdate {
	if v != nil {
		_u.SetReviewPending(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *PaymentTransactionClaimUpdate) SetEvidence(v map[string]interface{}) *PaymentTransactionClaimUpdate {
	_u.mutation.SetEvidence(v)
	return _u
}

// ClearEvidence clears the value of the "evidence" field.
func (_u *PaymentTransactionClaimUpdate) ClearEvidence() *PaymentTransactionClaimUpdate {
	_u.mutation.ClearEvidence()
	return _u
}

// Mutation returns the PaymentTransactionClaimMutation object of the builder.
func (_u *PaymentTransactionClaimUpdate) Mutation() *PaymentTransactionClaimMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentTransactionClaimUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentTransactionClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentTransactionClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentTransactionClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PaymentTransactionClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymenttransactionclaim.Table, paymenttransactionclaim.Columns, sqlgraph.NewFieldSpec(paymenttransactionclaim.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(paymenttransactionclaim.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.TransferTime(); ok {
		_spec.SetField(paymenttransactionclaim.FieldTransferTime, field.TypeTime, value)
	}
	if _u.mutation.TransferTimeCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldTransferTime, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderCreatedAt(); ok {
		_spec.SetField(paymenttransactionclaim.FieldOrderCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCreatedAtCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldOrderCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderWindowEnd(); ok {
		_spec.SetField(paymenttransactionclaim.FieldOrderWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.OrderWindowEndCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldOrderWindowEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewPending(); ok {
		_spec.SetField(paymenttransactionclaim.FieldReviewPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(paymenttransactionclaim.FieldEvidence, field.TypeJSON, value)
	}
	if _u.mutation.EvidenceCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldEvidence, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymenttransactionclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentTransactionClaimUpdateOne is the builder for updating a single PaymentTransactionClaim entity.
type PaymentTransactionClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentTransactionClaimMutation
}

// SetSource sets the "source" field.
func (_u *PaymentTransactionClaimUpdateOne) SetSource(v string) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdateOne) SetNillableSource(v *string) *PaymentTransactionClaimUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTransferTime sets the "transfer_time" field.
func (_u *PaymentTransactionClaimUpdateOne) SetTransferTime(v time.Time) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetTransferTime(v)
	return _u
}

// SetNillableTransferTime sets the "transfer_time" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdateOne) SetNillableTransferTime(v *time.Time) *PaymentTransactionClaimUpdateOne {
	if v != nil {
		_u.SetTransferTime(*v)
	}
	return _u
}

// ClearTransferTime clears the value of the "transfer_time" field.
func (_u *PaymentTransactionClaimUpdateOne) ClearTransferTime() *PaymentTransactionClaimUpdateOne {
	_u.mutation.ClearTransferTime()
	return _u
}

// SetOrderCreatedAt sets the "order_created_at" field.
func (_u *PaymentTransactionClaimUpdateOne) SetOrderCreatedAt(v time.Time) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetOrderCreatedAt(v)
	return _u
}

// SetNillableOrderCreatedAt sets the "order_created_at" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdateOne) SetNillableOrderCreatedAt(v *time.Time) *PaymentTransactionClaimUpdateOne {
	if v != nil {
		_u.SetOrderCreatedAt(*v)
	}
	return _u
}

// ClearOrderCreatedAt clears the value of the "order_created_at" field.
func (_u *PaymentTransactionClaimUpdateOne) ClearOrderCreatedAt() *PaymentTransactionClaimUpdateOne {
	_u.mutation.ClearOrderCreatedAt()
	return _u
}

// SetOrderWindowEnd sets the "order_window_end" field.
func (_u *PaymentTransactionClaimUpdateOne) SetOrderWindowEnd(v time.Time) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetOrderWindowEnd(v)
	return _u
}

// SetNillableOrderWindowEnd sets the "order_window_end" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdateOne) SetNillableOrderWindowEnd(v *time.Time) *PaymentTransactionClaimUpdateOne {
	if v != nil {
		_u.SetOrderWindowEnd(*v)
	}
	return _u
}

// ClearOrderWindowEnd clears the value of the "order_window_end" field.
func (_u *PaymentTransactionClaimUpdateOne) ClearOrderWindowEnd() *PaymentTransactionClaimUpdateOne {
	_u.mutation.ClearOrderWindowEnd()
	return _u
}

// SetReviewPending sets the "review_pending" field.
func (_u *PaymentTransactionClaimUpdateOne) SetReviewPending(v bool) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetReviewPending(v)
	return _u
}

// SetNillableReviewPending sets the "review_pending" field if the given value is not nil.
func (_u *PaymentTransactionClaimUpdateOne) SetNillableReviewPending(v *bool) *PaymentTransactionClaimUpdateOne {
	if v != nil {
		_u.SetReviewPending(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *PaymentTransactionClaimUpdateOne) SetEvidence(v map[string]interface{}) *PaymentTransactionClaimUpdateOne {
	_u.mutation.SetEvidence(v)
	return _u
}

// ClearEvidence clears the value of the "evidence" field.
func (_u *PaymentTransactionClaimUpdateOne) ClearEvidence() *PaymentTransactionClaimUpdateOne {
	_u.mutation.ClearEvidence()
	return _u
}

// Mutation returns the PaymentTransactionClaimMutation object of the builder.
func (_u *PaymentTransactionClaimUpdateOne) Mutation() *PaymentTransactionClaimMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentTransactionClaimUpdate builder.
func (_u *PaymentTransactionClaimUpdateOne) Where(ps ...predicate.PaymentTransactionClaim) *PaymentTransactionClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentTransactionClaimUpdateOne) Select(field string, fields ...string) *PaymentTransactionClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentTransactionClaim entity.
func (_u *PaymentTransactionClaimUpdateOne) Save(ctx context.Context) (*PaymentTransactionClaim, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentTransactionClaimUpdateOne) SaveX(ctx context.Context) *PaymentTransactionClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentTransactionClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentTransactionClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PaymentTransactionClaimUpdateOne) sqlSave(ctx context.Context) (_node *PaymentTransactionClaim, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymenttransactionclaim.Table, paymenttransactionclaim.Columns, sqlgraph.NewFieldSpec(paymenttransactionclaim.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentTransactionClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymenttransactionclaim.FieldID)
		for _, f := range fields {
			if !paymenttransactionclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymenttransactionclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(paymenttransactionclaim.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.TransferTime(); ok {
		_spec.SetField(paymenttransactionclaim.FieldTransferTime, field.TypeTime, value)
	}
	if _u.mutation.TransferTimeCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldTransferTime, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderCreatedAt(); ok {
		_spec.SetField(paymenttransactionclaim.FieldOrderCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCreatedAtCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldOrderCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderWindowEnd(); ok {
		_spec.SetField(paymenttransactionclaim.FieldOrderWindowEnd, field.TypeTime, value)
	}
	if _u.mutation.OrderWindowEndCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldOrderWindowEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewPending(); ok {
		_spec.SetField(paymenttransactionclaim.FieldReviewPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(paymenttransactionclaim.FieldEvidence, field.TypeJSON, value)
	}
	if _u.mutation.EvidenceCleared() {
		_spec.ClearField(paymenttransactionclaim.FieldEvidence, field.TypeJSON)
	}
	_node = &PaymentTransactionClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymenttransactionclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
