// Code generated by ent, DO NOT EDIT.

package intentrouter

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the intentrouter type in the database.
	Label = "intent_router"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldClassifierBaseURL holds the string denoting the classifier_base_url field in the database.
	FieldClassifierBaseURL = "classifier_base_url"
	// FieldClassifierAPIKey holds the string denoting the classifier_api_key field in the database.
	FieldClassifierAPIKey = "classifier_api_key"
	// FieldClassifierProtocol holds the string denoting the classifier_protocol field in the database.
	FieldClassifierProtocol = "classifier_protocol"
	// FieldClassifierModel holds the string denoting the classifier_model field in the database.
	FieldClassifierModel = "classifier_model"
	// FieldClassifierTimeoutMs holds the string denoting the classifier_timeout_ms field in the database.
	FieldClassifierTimeoutMs = "classifier_timeout_ms"
	// FieldCacheTTLSeconds holds the string denoting the cache_ttl_seconds field in the database.
	FieldCacheTTLSeconds = "cache_ttl_seconds"
	// FieldMaxInputChars holds the string denoting the max_input_chars field in the database.
	FieldMaxInputChars = "max_input_chars"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// Table holds the table name of the intentrouter in the database.
	Table = "intent_routers"
)

// Columns holds all SQL columns for intentrouter fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldEnabled,
	FieldClassifierBaseURL,
	FieldClassifierAPIKey,
	FieldClassifierProtocol,
	FieldClassifierModel,
	FieldClassifierTimeoutMs,
	FieldCacheTTLSeconds,
	FieldMaxInputChars,
	FieldRules,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultClassifierBaseURL holds the default value on creation for the "classifier_base_url" field.
	DefaultClassifierBaseURL string
	// ClassifierBaseURLValidator is a validator for the "classifier_base_url" field. It is called by the builders before save.
	ClassifierBaseURLValidator func(string) error
	// DefaultClassifierAPIKey holds the default value on creation for the "classifier_api_key" field.
	DefaultClassifierAPIKey string
	// ClassifierAPIKeyValidator is a validator for the "classifier_api_key" field. It is called by the builders before save.
	ClassifierAPIKeyValidator func(string) error
	// DefaultClassifierProtocol holds the default value on creation for the "classifier_protocol" field.
	DefaultClassifierProtocol string
	// ClassifierProtocolValidator is a validator for the "classifier_protocol" field. It is called by the builders before save.
	ClassifierProtocolValidator func(string) error
	// DefaultClassifierModel holds the default value on creation for the "classifier_model" field.
	DefaultClassifierModel string
	// ClassifierModelValidator is a validator for the "classifier_model" field. It is called by the builders before save.
	ClassifierModelValidator func(string) error
	// DefaultClassifierTimeoutMs holds the default value on creation for the "classifier_timeout_ms" field.
	DefaultClassifierTimeoutMs int
	// DefaultCacheTTLSeconds holds the default value on creation for the "cache_ttl_seconds" field.
	DefaultCacheTTLSeconds int
	// DefaultMaxInputChars holds the default value on creation for the "max_input_chars" field.
	DefaultMaxInputChars int
)

// OrderOption defines the ordering options for the IntentRouter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByClassifierBaseURL orders the results by the classifier_base_url field.
func ByClassifierBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassifierBaseURL, opts...).ToFunc()
}

// ByClassifierAPIKey orders the results by the classifier_api_key field.
func ByClassifierAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassifierAPIKey, opts...).ToFunc()
}

// ByClassifierProtocol orders the results by the classifier_protocol field.
func ByClassifierProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassifierProtocol, opts...).ToFunc()
}

// ByClassifierModel orders the results by the classifier_model field.
func ByClassifierModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassifierModel, opts...).ToFunc()
}

// ByClassifierTimeoutMs orders the results by the classifier_timeout_ms field.
func ByClassifierTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassifierTimeoutMs, opts...).ToFunc()
}

// ByCacheTTLSeconds orders the results by the cache_ttl_seconds field.
func ByCacheTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheTTLSeconds, opts...).ToFunc()
}

// ByMaxInputChars orders the results by the max_input_chars field.
func ByMaxInputChars(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxInputChars, opts...).ToFunc()
}
