// Code generated by ent, DO NOT EDIT.

package intentrouter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldEnabled, v))
}

// ClassifierBaseURL applies equality check predicate on the "classifier_base_url" field. It's identical to ClassifierBaseURLEQ.
func ClassifierBaseURL(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierBaseURL, v))
}

// ClassifierAPIKey applies equality check predicate on the "classifier_api_key" field. It's identical to ClassifierAPIKeyEQ.
func ClassifierAPIKey(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierAPIKey, v))
}

// ClassifierProtocol applies equality check predicate on the "classifier_protocol" field. It's identical to ClassifierProtocolEQ.
func ClassifierProtocol(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierProtocol, v))
}

// ClassifierModel applies equality check predicate on the "classifier_model" field. It's identical to ClassifierModelEQ.
func ClassifierModel(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierModel, v))
}

// ClassifierTimeoutMs applies equality check predicate on the "classifier_timeout_ms" field. It's identical to ClassifierTimeoutMsEQ.
func ClassifierTimeoutMs(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierTimeoutMs, v))
}

// CacheTTLSeconds applies equality check predicate on the "cache_ttl_seconds" field. It's identical to CacheTTLSecondsEQ.
func CacheTTLSeconds(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldCacheTTLSeconds, v))
}

// MaxInputChars applies equality check predicate on the "max_input_chars" field. It's identical to MaxInputCharsEQ.
func MaxInputChars(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldMaxInputChars, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldGroupID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldEnabled, v))
}

// ClassifierBaseURLEQ applies the EQ predicate on the "classifier_base_url" field.
func ClassifierBaseURLEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLNEQ applies the NEQ predicate on the "classifier_base_url" field.
func ClassifierBaseURLNEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLIn applies the In predicate on the "classifier_base_url" field.
func ClassifierBaseURLIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldClassifierBaseURL, vs...))
}

// ClassifierBaseURLNotIn applies the NotIn predicate on the "classifier_base_url" field.
func ClassifierBaseURLNotIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldClassifierBaseURL, vs...))
}

// ClassifierBaseURLGT applies the GT predicate on the "classifier_base_url" field.
func ClassifierBaseURLGT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLGTE applies the GTE predicate on the "classifier_base_url" field.
func ClassifierBaseURLGTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLLT applies the LT predicate on the "classifier_base_url" field.
func ClassifierBaseURLLT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLLTE applies the LTE predicate on the "classifier_base_url" field.
func ClassifierBaseURLLTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLContains applies the Contains predicate on the "classifier_base_url" field.
func ClassifierBaseURLContains(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContains(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLHasPrefix applies the HasPrefix predicate on the "classifier_base_url" field.
func ClassifierBaseURLHasPrefix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasPrefix(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLHasSuffix applies the HasSuffix predicate on the "classifier_base_url" field.
func ClassifierBaseURLHasSuffix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasSuffix(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLEqualFold applies the EqualFold predicate on the "classifier_base_url" field.
func ClassifierBaseURLEqualFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEqualFold(FieldClassifierBaseURL, v))
}

// ClassifierBaseURLContainsFold applies the ContainsFold predicate on the "classifier_base_url" field.
func ClassifierBaseURLContainsFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContainsFold(FieldClassifierBaseURL, v))
}

// ClassifierAPIKeyEQ applies the EQ predicate on the "classifier_api_key" field.
func ClassifierAPIKeyEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyNEQ applies the NEQ predicate on the "classifier_api_key" field.
func ClassifierAPIKeyNEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyIn applies the In predicate on the "classifier_api_key" field.
func ClassifierAPIKeyIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldClassifierAPIKey, vs...))
}

// ClassifierAPIKeyNotIn applies the NotIn predicate on the "classifier_api_key" field.
func ClassifierAPIKeyNotIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldClassifierAPIKey, vs...))
}

// ClassifierAPIKeyGT applies the GT predicate on the "classifier_api_key" field.
func ClassifierAPIKeyGT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyGTE applies the GTE predicate on the "classifier_api_key" field.
func ClassifierAPIKeyGTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyLT applies the LT predicate on the "classifier_api_key" field.
func ClassifierAPIKeyLT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyLTE applies the LTE predicate on the "classifier_api_key" field.
func ClassifierAPIKeyLTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyContains applies the Contains predicate on the "classifier_api_key" field.
func ClassifierAPIKeyContains(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContains(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyHasPrefix applies the HasPrefix predicate on the "classifier_api_key" field.
func ClassifierAPIKeyHasPrefix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasPrefix(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyHasSuffix applies the HasSuffix predicate on the "classifier_api_key" field.
func ClassifierAPIKeyHasSuffix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasSuffix(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyEqualFold applies the EqualFold predicate on the "classifier_api_key" field.
func ClassifierAPIKeyEqualFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEqualFold(FieldClassifierAPIKey, v))
}

// ClassifierAPIKeyContainsFold applies the ContainsFold predicate on the "classifier_api_key" field.
func ClassifierAPIKeyContainsFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContainsFold(FieldClassifierAPIKey, v))
}

// ClassifierProtocolEQ applies the EQ predicate on the "classifier_protocol" field.
func ClassifierProtocolEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierProtocol, v))
}

// ClassifierProtocolNEQ applies the NEQ predicate on the "classifier_protocol" field.
func ClassifierProtocolNEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldClassifierProtocol, v))
}

// ClassifierProtocolIn applies the In predicate on the "classifier_protocol" field.
func ClassifierProtocolIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldClassifierProtocol, vs...))
}

// ClassifierProtocolNotIn applies the NotIn predicate on the "classifier_protocol" field.
func ClassifierProtocolNotIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldClassifierProtocol, vs...))
}

// ClassifierProtocolGT applies the GT predicate on the "classifier_protocol" field.
func ClassifierProtocolGT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldClassifierProtocol, v))
}

// ClassifierProtocolGTE applies the GTE predicate on the "classifier_protocol" field.
func ClassifierProtocolGTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldClassifierProtocol, v))
}

// ClassifierProtocolLT applies the LT predicate on the "classifier_protocol" field.
func ClassifierProtocolLT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldClassifierProtocol, v))
}

// ClassifierProtocolLTE applies the LTE predicate on the "classifier_protocol" field.
func ClassifierProtocolLTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldClassifierProtocol, v))
}

// ClassifierProtocolContains applies the Contains predicate on the "classifier_protocol" field.
func ClassifierProtocolContains(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContains(FieldClassifierProtocol, v))
}

// ClassifierProtocolHasPrefix applies the HasPrefix predicate on the "classifier_protocol" field.
func ClassifierProtocolHasPrefix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasPrefix(FieldClassifierProtocol, v))
}

// ClassifierProtocolHasSuffix applies the HasSuffix predicate on the "classifier_protocol" field.
func ClassifierProtocolHasSuffix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasSuffix(FieldClassifierProtocol, v))
}

// ClassifierProtocolEqualFold applies the EqualFold predicate on the "classifier_protocol" field.
func ClassifierProtocolEqualFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEqualFold(FieldClassifierProtocol, v))
}

// ClassifierProtocolContainsFold applies the ContainsFold predicate on the "classifier_protocol" field.
func ClassifierProtocolContainsFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContainsFold(FieldClassifierProtocol, v))
}

// ClassifierModelEQ applies the EQ predicate on the "classifier_model" field.
func ClassifierModelEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierModel, v))
}

// ClassifierModelNEQ applies the NEQ predicate on the "classifier_model" field.
func ClassifierModelNEQ(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldClassifierModel, v))
}

// ClassifierModelIn applies the In predicate on the "classifier_model" field.
func ClassifierModelIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldClassifierModel, vs...))
}

// ClassifierModelNotIn applies the NotIn predicate on the "classifier_model" field.
func ClassifierModelNotIn(vs ...string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldClassifierModel, vs...))
}

// ClassifierModelGT applies the GT predicate on the "classifier_model" field.
func ClassifierModelGT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldClassifierModel, v))
}

// ClassifierModelGTE applies the GTE predicate on the "classifier_model" field.
func ClassifierModelGTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldClassifierModel, v))
}

// ClassifierModelLT applies the LT predicate on the "classifier_model" field.
func ClassifierModelLT(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldClassifierModel, v))
}

// ClassifierModelLTE applies the LTE predicate on the "classifier_model" field.
func ClassifierModelLTE(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldClassifierModel, v))
}

// ClassifierModelContains applies the Contains predicate on the "classifier_model" field.
func ClassifierModelContains(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContains(FieldClassifierModel, v))
}

// ClassifierModelHasPrefix applies the HasPrefix predicate on the "classifier_model" field.
func ClassifierModelHasPrefix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasPrefix(FieldClassifierModel, v))
}

// ClassifierModelHasSuffix applies the HasSuffix predicate on the "classifier_model" field.
func ClassifierModelHasSuffix(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldHasSuffix(FieldClassifierModel, v))
}

// ClassifierModelEqualFold applies the EqualFold predicate on the "classifier_model" field.
func ClassifierModelEqualFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEqualFold(FieldClassifierModel, v))
}

// ClassifierModelContainsFold applies the ContainsFold predicate on the "classifier_model" field.
func ClassifierModelContainsFold(v string) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldContainsFold(FieldClassifierModel, v))
}

// ClassifierTimeoutMsEQ applies the EQ predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldClassifierTimeoutMs, v))
}

// ClassifierTimeoutMsNEQ applies the NEQ predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsNEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldClassifierTimeoutMs, v))
}

// ClassifierTimeoutMsIn applies the In predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldClassifierTimeoutMs, vs...))
}

// ClassifierTimeoutMsNotIn applies the NotIn predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsNotIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldClassifierTimeoutMs, vs...))
}

// ClassifierTimeoutMsGT applies the GT predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsGT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldClassifierTimeoutMs, v))
}

// ClassifierTimeoutMsGTE applies the GTE predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsGTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldClassifierTimeoutMs, v))
}

// ClassifierTimeoutMsLT applies the LT predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsLT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldClassifierTimeoutMs, v))
}

// ClassifierTimeoutMsLTE applies the LTE predicate on the "classifier_timeout_ms" field.
func ClassifierTimeoutMsLTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldClassifierTimeoutMs, v))
}

// CacheTTLSecondsEQ applies the EQ predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsNEQ applies the NEQ predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsNEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsIn applies the In predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldCacheTTLSeconds, vs...))
}

// CacheTTLSecondsNotIn applies the NotIn predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsNotIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldCacheTTLSeconds, vs...))
}

// CacheTTLSecondsGT applies the GT predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsGT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsGTE applies the GTE predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsGTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsLT applies the LT predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsLT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsLTE applies the LTE predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsLTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldCacheTTLSeconds, v))
}

// MaxInputCharsEQ applies the EQ predicate on the "max_input_chars" field.
func MaxInputCharsEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldEQ(FieldMaxInputChars, v))
}

// MaxInputCharsNEQ applies the NEQ predicate on the "max_input_chars" field.
func MaxInputCharsNEQ(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNEQ(FieldMaxInputChars, v))
}

// MaxInputCharsIn applies the In predicate on the "max_input_chars" field.
func MaxInputCharsIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIn(FieldMaxInputChars, vs...))
}

// MaxInputCharsNotIn applies the NotIn predicate on the "max_input_chars" field.
func MaxInputCharsNotIn(vs ...int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotIn(FieldMaxInputChars, vs...))
}

// MaxInputCharsGT applies the GT predicate on the "max_input_chars" field.
func MaxInputCharsGT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGT(FieldMaxInputChars, v))
}

// MaxInputCharsGTE applies the GTE predicate on the "max_input_chars" field.
func MaxInputCharsGTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldGTE(FieldMaxInputChars, v))
}

// MaxInputCharsLT applies the LT predicate on the "max_input_chars" field.
func MaxInputCharsLT(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLT(FieldMaxInputChars, v))
}

// MaxInputCharsLTE applies the LTE predicate on the "max_input_chars" field.
func MaxInputCharsLTE(v int) predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldLTE(FieldMaxInputChars, v))
}

// RulesIsNil applies the IsNil predicate on the "rules" field.
func RulesIsNil() predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldIsNull(FieldRules))
}

// RulesNotNil applies the NotNil predicate on the "rules" field.
func RulesNotNil() predicate.IntentRouter {
	return predicate.IntentRouter(sql.FieldNotNull(FieldRules))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntentRouter) predicate.IntentRouter {
	return predicate.IntentRouter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntentRouter) predicate.IntentRouter {
	return predicate.IntentRouter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntentRouter) predicate.IntentRouter {
	return predicate.IntentRouter(sql.NotPredicates(p))
}
